service: receeve

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  localstack:
    debug: true
    stages:
      - local
      - dev

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  emailEvent:
    handler: handler.emailEventHandler
    events:
      - http:
          method: post
          path: emailevent
